# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4098"]
  end

  config.vm.box = 'bb-learn-9.1.201410.160373'
  config.vm.box_url = './bb-learn-9.1.201410.160373.box'

  config.vm.network :forwarded_port, guest: 8080, host: 9876
  config.vm.network :forwarded_port, guest: 8443, host: 9877
  config.vm.network :forwarded_port, guest: 2222, host: 9878
  config.vm.network :forwarded_port, guest: 5432, host: 9879

  # port forwarding added for integration testing using JUnit
  # note that this will conflict if you have PostgreSQL running
  # on your host system
  config.vm.network :forwarded_port, guest: 5432, host: 5432
end
